services:
  emco-client:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 5173:5173
    links:
      - emco-server
    depends_on:
      - emco-server
  emco-server:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 3000:3000
    links:
      - emco-mongodb
    depends_on:
      - emco-mongodb
  emco-mongodb:
    container_name: emco-mongodb
    image: mongo
    ports:
      - 27017:27017
